version: '3'

services:
  base: &base
    image: ghcr.io/brandpatch/chatwoot-brandpatch:test
    env_file: .env
    volumes:
      - storage_data:/app/storage
      - ./custom-brand/assets/logo.svg:/app/public/brand-assets/logo.svg:ro
      - ./custom-brand/assets/logo.svg:/app/public/brand-assets/logo_dark.svg:ro
      - ./custom-brand/assets/logo.svg:/app/public/brand-assets/logo_light.svg:ro
      - ./custom-brand/assets/logo.svg:/app/public/brand-assets/logo_thumbnail.svg:ro
      - ./custom-brand/assets/favicon-16x16.png:/app/public/favicon-16x16.png:ro
      - ./custom-brand/assets/favicon-32x32.png:/app/public/favicon-32x32.png:ro
      # CUSTOM CSS
      - ./custom-brand/custom.css:/app/public/brand-assets/custom.css:ro

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:6379:6379'

volumes:
  storage_data:
  postgres_data:
  redis_data:
